spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
app:
  arquivo: file:files/clientes.txt